# UCI Repo
uci_repo:
  uci_repo_code: 348273923908294

# Data Configuration
data:
  raw_data_path: bank_marketing_e2e_model/data/raw_training_data.csv
  train_data_path: bank_marketing_e2e_model/data/train.csv
  test_data_path: bank_marketing_e2e_model/data/test.csv

# Model Configuration
model:
  hyperparameters:
    C: 0.5
    random_state: 420

# Output Configuration
output:
  model_path: bank_marketing_e2e_model/models/model/model_pipeline.joblib
  model_performance_path: bank_marketing_e2e_model/models/model_performance/model_metrics.json

# App Configuration
app:
  app_input_schema_path: bank_marketing_e2e_model/app/app_input_schema.json
